dist: xenial

language: go

env:
  - GO111MODULE=on

go:
  - 1.11.x

git:
  depth: 1

install: true

notifications:
  email: false

before_script:
  - go get -u github.com/golangci/golangci-lint/cmd/golangci-lint
  - go get -u github.com/onsi/ginkgo/ginkgo  # installs the ginkgo CLI
  - go get -u github.com/onsi/gomega/...     # fetches the matcher library


script:
  - golangci-lint run       # run a bunch of code checkers/linters in parallel
  - ginkgo -r --randomizeAllSpecs --randomizeSuites --failOnPending --cover --trace --race --progress
  - go build                # build it

after_success:
  - touch coverage.txt; find . -name "*.coverprofile" | xargs -l cat >> coverage.txt
  - curl -s https://codecov.io/bash | bash -
